#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-RSclient
Version  : 0.7.9
Release  : 52
URL      : https://cran.r-project.org/src/contrib/RSclient_0.7-9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RSclient_0.7-9.tar.gz
Summary  : Client for Rserve
Group    : Development/Tools
License  : GPL-2.0
Requires: R-RSclient-lib = %{version}-%{release}
Requires: R-RSclient-license = %{version}-%{release}
BuildRequires : buildreq-R
BuildRequires : openssl-dev

%description
No detailed description available

%package lib
Summary: lib components for the R-RSclient package.
Group: Libraries
Requires: R-RSclient-license = %{version}-%{release}

%description lib
lib components for the R-RSclient package.


%package license
Summary: license components for the R-RSclient package.
Group: Default

%description license
license components for the R-RSclient package.


%prep
%setup -q -n RSclient
cd %{_builddir}/RSclient

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1669831308

%install
export SOURCE_DATE_EPOCH=1669831308
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-RSclient
cp %{_builddir}/RSclient/LICENSE %{buildroot}/usr/share/package-licenses/R-RSclient/11954460076d355c9d44285104086796a8181c21 || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RSclient/DESCRIPTION
/usr/lib64/R/library/RSclient/INDEX
/usr/lib64/R/library/RSclient/LICENSE
/usr/lib64/R/library/RSclient/Meta/Rd.rds
/usr/lib64/R/library/RSclient/Meta/features.rds
/usr/lib64/R/library/RSclient/Meta/hsearch.rds
/usr/lib64/R/library/RSclient/Meta/links.rds
/usr/lib64/R/library/RSclient/Meta/nsInfo.rds
/usr/lib64/R/library/RSclient/Meta/package.rds
/usr/lib64/R/library/RSclient/NAMESPACE
/usr/lib64/R/library/RSclient/NEWS
/usr/lib64/R/library/RSclient/R/RSclient
/usr/lib64/R/library/RSclient/R/RSclient.rdb
/usr/lib64/R/library/RSclient/R/RSclient.rdx
/usr/lib64/R/library/RSclient/help/AnIndex
/usr/lib64/R/library/RSclient/help/RSclient.rdb
/usr/lib64/R/library/RSclient/help/RSclient.rdx
/usr/lib64/R/library/RSclient/help/aliases.rds
/usr/lib64/R/library/RSclient/help/paths.rds
/usr/lib64/R/library/RSclient/html/00Index.html
/usr/lib64/R/library/RSclient/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/RSclient/libs/RSclient.so
/usr/lib64/R/library/RSclient/libs/RSclient.so.avx2
/usr/lib64/R/library/RSclient/libs/RSclient.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-RSclient/11954460076d355c9d44285104086796a8181c21
